#:schema node_modules/wrangler/config-schema.json
name = "test"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true


[vars]
enableOriginS3 = true
S3_ENDPOINT = ""  # 填入S3回源endpoint
S3_BUCKET_NAME = "" # 填入S3回源存储桶
S3_REGION = "" # 填入S3 region
S3_ACCESS_KEY_ID = "" # 填入S3 key id
TG_CHAT_ID= "" # 填入TG频道id

[[d1_databases]]
binding = "DB" # 不要改动
database_name = "" # 填入你在cloudflare创建的d1数据库名称
database_id = "xxxx-xxxx-xxxx-xxx-xxxxx" # 填入你在cloudflare创建的d1数据库id